name: Sports Gambling Cron

on:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # needed to push
          fetch-depth: 0            # fetch full history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas requests

      - name: Run cron1.py
        run: |
          mkdir -p data
          python scripts/cron1.py

      - name: Commit new CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --cached --quiet || git commit -m "Add new CSVs from cron run $(date)"
          git push
