name: Run cron1 every 2 hours

on:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours (UTC)
  workflow_dispatch: {}    # manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      ODDS_1: ${{ secrets.ODDS_1 }}
      ODDS_2: ${{ secrets.ODDS_2 }}  # optional additional keys

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
