name: Run cron1 every 2 hours

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run cron1.py and print logs
        env:
          ODDS_1: ${{ secrets.ODDS_1 }}
          ODDS_2: ${{ secrets.ODDS_2 }}
        run: |
          mkdir -p logs
          echo "Running script..."
          python scripts/cron1.py | tee logs/cron1.log
          echo "=== END OF LOG OUTPUT ==="
