name: Sports Gambling Cron

on:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      # Step 4: Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}


      # Step 5: Run cron1.py
      - name: Run cron1.py
        run: |
          mkdir -p data
          python scripts/cron1.py

      # Step 6: Commit and push new CSVs
      - name: Commit and push new CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --cached --quiet || git commit -m "Add new CSVs from cron run $(date)"
          git push git@github.com:fungusoRE5enX/sports_gambling.git main
